name: sum-ci-workflow
on: 
  pull_request:
    branches:
      - main
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.0'
      - run: go test
      - run: go run math.go

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        id: build_docker
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: bruandreo/sum-ci:latest